config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :games

  root 'pages#homepage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players
  has_many :rolls

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_params)

    if @game.save
      flash[:success] = 'Game created'
      redirect_to games_path
    else
      respond_to do |format|
        format.js do
          render :new, content_type: 'text/html'
        end
      end
    end
  end

  private

  def game_params
    params.require(:game).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    request.path == test_path ? 'active' : ''
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/_form.slim
.container
  = form_with model: @game, class: 'mt-4' do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control', placeholder: 'Enter Name'

    .text-right
      = link_to 'Cancel', games_path, class: 'btn btn-secondary mr-1'
      = f.submit 'Save', class: 'btn btn-success'

app/views/games/index.slim
.container
  h1.display-6 Games

  = link_to 'New Game', new_game_path, class: 'btn btn-primary'

  ul
    - @games.each do |game|
      li = game.name

app/views/games/new.slim
= render 'form'

app/views/layouts/application.html.slim
html
  head
    title Risk Calculator
    = csrf_meta_tags
    = csp_meta_tag
    meta name='viewport' content='width=device-width, initial-scale=1'

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
      a.navbar-brand href='/'  Risk Calculator
      button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
        span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        ul.navbar-nav.mr-auto
          li.nav-item class=current_class?(games_path)
            = link_to 'Games', games_path, class: 'nav-link'
          / - active = request.path_info == '/calculate' ? 'active' : ''
          / li.nav-item class=active
          /   a.nav-link href='/calculate' Calculate Luck

          / - active = request.path_info == '/load' ? 'active' : ''
          / li.nav-item class=active
          /   a.nav-link href='/load' Load Game
    .body
      - flash.each do |key, value|
        .alert class="alert-#{key}" = value
      = yield
    .footer.navbar.navbar-dark.bg-primary
      span.navbar-text.p-0 Copyright © 2019 Josh McLeod & Jeremy Walton

app/views/pages/homepage.slim
.container
  h1.display-6 Welcome to our luck calculator for the Risk board game!

  .row.mb-1
    .col-md-6
      img.img-fluid src='https://gazettereview.com/wp-content/uploads/2017/03/Risk-Featured-e1488483112745.jpg' alt='Card image cap'
    .col-md-6
      p Have you ever played Risk with your friends and felt like you were overwhemingly unlucky (or lucky)
          with your rolls? Well now is your chance to prove it! We have created a simple tool that allows you to keep track
          of each roll as you play the game, and displays stats showing how lucky or unlucky each player was!
      p It works by calculating adjusted wins and adjusted losses that account for how many dice were rolled and not just a
        straight win or loss. For instance, if Bob beats Jim in a 1 to 3 roll, he was a lot more lucky then if it had been
        a 1 to 1 roll. Therefore his adjusted wins will go up by 3 while his normal wins only goes up by 1.
      p To get started, click on "Calculate Luck" at the top right of the page. To input a roll, first add the players,
        then use the dropdowns to select the appropriate choices. Then click "Process Roll."